---
title: "Discussion"
---

> Starting with my first prediction that there would be higher overall satisfaction with an entire home rather than a private room was not confirmed by the data, rather there was a statistically higher overall satisfaction score associated with a private room. A shared room did not statistically differ from the overall satisfaction of a whole home. Practically speaking, the difference in overall satisfaction, .05, increase could be seen as negligible.   There was a wide range of values for the 122 different neighborhoods that were listed, and the largest positive change in overall satisfaction came from listings in Somerton, est. = .847 p = .0000001, and listings with the largest negative change in overall satisfaction were from Morrell Park, est. = -.690 p = .045. Even with other scores not changing as much from the overall estimate, neighborhood choices does have a strong argument for practical changes of satisfaction of the stay, and for a majority of neighborhoods, should affect choices of where to rent an Airbnb, if considering only predicted satisfaction with the stay. Moving to reviews, there was a statistical change in overall satisfaction of a stay of .0003, p = .00001, for every additional review that the listing received, and just like accommodation type, there may be less than interesting practical significance to a very small change in overall satisfaction given the vast numbers of reviews to gain even a .01 change in overall satisfaction rating. Lastly, price was also statistically significant at changing the overall review by .0002 for every dollar increase in the listing's price, p = .000000000002.

---

> This analysis can shed some light on what factors may play a role in changing the overall satisfaction of a stay. Although this analysis covered some of the features of a stay that may play a role in how likely a factor predicts a good stay at an Airbnb, there are more that could be analyzed in addition to the ones put forth here. First, host id was not used, but could be a predictor of satisfaction, as perhaps some landlords have listings that are on average better than others. Latitude and Longitude could be used to see finer grain detail of neighborhood ratings. Perhaps a neighborhood has areas that have high scores and low ones, but because this analysis only used the neighborhood as a whole, this analysis could miss valuable insights like this. There could also be value in understanding socio-economic status of the neighborhood or the crime rate that may also dictate how the guest thought the stay should be rated. These would be interesting topics to explore further.